name: arb_tsv
description: This package provides conversion between arb files and tsv files and merging arb files for easy internationalization.
version: 2.0.1
homepage: https://github.com/flutterstudygn/arb_tsv

environment:
  sdk: '>=2.13.0 <3.0.0'
  
dependencies:
  args: ">=2.1.1 <3.0.0"
  path: ">=1.8.0 <2.0.0"

dev_dependencies:
  lints: ">=1.0.1 <2.0.0"
