name: arb_tsv
description: arb <-> tsv converter
version: 0.1.0
homepage: https://github.com/flutterstudygn/arb_tsv

environment:
  sdk: '>=2.8.1 <3.0.0'
  
dependencies:
  args: ^1.6.0
  
  path: ^1.7.0

  intl:
  intl_translation: ^0.17.10

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
